name: ioncast
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=3_kmp_llvm
  - alsa-lib=1.2.14=hb9d3cd8_0
  - aom=3.9.1=hac33072_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attr=2.5.1=h166bdaf_1
  - aws-c-auth=0.9.0=h92a005d_16
  - aws-c-cal=0.9.2=he7b75e1_1
  - aws-c-common=0.12.4=hb03c661_0
  - aws-c-compression=0.3.1=h92c474e_6
  - aws-c-event-stream=0.5.5=h0c2b49e_1
  - aws-c-http=0.10.2=hee85082_3
  - aws-c-io=0.21.0=h1d8da38_1
  - aws-c-mqtt=0.13.1=h46c1de9_4
  - aws-c-s3=0.8.3=h9cdc349_1
  - aws-c-sdkutils=0.2.4=h92c474e_1
  - aws-checksums=0.2.7=h92c474e_2
  - aws-crt-cpp=0.32.10=h186f887_3
  - aws-sdk-cpp=1.11.510=h379b65b_14
  - azure-core-cpp=1.14.0=h5cfcd09_0
  - azure-identity-cpp=1.10.0=h113e628_0
  - azure-storage-blobs-cpp=12.13.0=h3cf044e_1
  - azure-storage-common-cpp=12.8.0=h736e048_1
  - azure-storage-files-datalake-cpp=12.12.0=ha633028_1
  - brotli=1.1.0=hb9d3cd8_3
  - brotli-bin=1.1.0=hb9d3cd8_3
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.7.14=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.2=py313h33d0bda_0
  - cpython=3.13.5=py313hd8ed1ab_102
  - cuda-cccl_linux-64=12.9.27=ha770c72_0
  - cuda-crt-tools=12.9.86=ha770c72_1
  - cuda-cudart=12.9.79=h5888daf_0
  - cuda-cudart-dev_linux-64=12.9.79=h3f2d84a_0
  - cuda-cudart-static_linux-64=12.9.79=h3f2d84a_0
  - cuda-cudart_linux-64=12.9.79=h3f2d84a_0
  - cuda-cuobjdump=12.9.82=hbd13f7d_0
  - cuda-cupti=12.9.79=h9ab20c4_0
  - cuda-nvcc-tools=12.9.86=he02047a_1
  - cuda-nvdisasm=12.9.88=hbd13f7d_0
  - cuda-nvrtc=12.9.86=h5888daf_0
  - cuda-nvtx=12.9.79=h5888daf_0
  - cuda-nvvm-tools=12.9.86=he02047a_1
  - cuda-version=12.9=h4f385c5_3
  - cudnn=9.10.1.4=h7646684_0
  - cupy=13.5.1=py313h586c94b_1
  - cupy-core=13.5.1=py313h9596e46_1
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h3c4dab8_0
  - debugpy=1.8.14=py313h46c70d0_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - double-conversion=3.3.1=h5888daf_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - fastrlock=0.8.3=py313h9800cb9_1
  - ffmpeg=7.1.1=gpl_hceff1ee_706
  - filelock=3.18.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.59.0=py313h3dea7bd_0
  - freeglut=3.2.2=ha6d2627_3
  - freetype=2.13.3=ha770c72_1
  - fribidi=1.0.10=h36c2ea0_0
  - fsspec=2025.7.0=pyhd8ed1ab_0
  - gdk-pixbuf=2.42.12=h7b179bb_1
  - gettext=0.25.1=h5888daf_0
  - gettext-tools=0.25.1=h5888daf_0
  - gflags=2.2.2=h5888daf_1005
  - giflib=5.2.2=hd590300_0
  - glog=0.7.1=hbabe93e_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py313h11186cd_0
  - graphite2=1.3.14=h5888daf_0
  - harfbuzz=11.2.1=h3beb420_0
  - hdf5=1.14.6=nompi_h6e4c0c1_102
  - icu=75.1=he02047a_0
  - imath=3.1.12=h7955e40_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=9.4.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jasper=4.2.5=h1920b20_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.8=py313h33d0bda_1
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h1423503_1
  - lerc=4.0.0=h0aef613_1
  - level-zero=1.23.1=h84d6215_0
  - libabseil=20250127.1=cxx17_hbbce691_0
  - libaec=1.1.4=h3f801dc_0
  - libarrow=20.0.0=h019e7cd_8_cuda
  - libarrow-acero=20.0.0=hb826db4_8_cuda
  - libarrow-dataset=20.0.0=hb826db4_8_cuda
  - libarrow-substrait=20.0.0=h69308b4_8_cuda
  - libasprintf=0.25.1=h8e693c7_0
  - libasprintf-devel=0.25.1=h8e693c7_0
  - libass=0.17.3=h52826cd_2
  - libavif16=1.3.0=h766b0b6_0
  - libblas=3.9.0=32_hfdb39a5_mkl
  - libbrotlicommon=1.1.0=hb9d3cd8_3
  - libbrotlidec=1.1.0=hb9d3cd8_3
  - libbrotlienc=1.1.0=hb9d3cd8_3
  - libcap=2.75=h39aace5_0
  - libcblas=3.9.0=32_h372d94f_mkl
  - libclang-cpp20.1=20.1.8=default_hddf928d_0
  - libclang13=20.1.8=default_ha444ac7_0
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=12.9.1.4=h9ab20c4_0
  - libcudnn=9.10.1.4=h4840ae0_0
  - libcudnn-dev=9.10.1.4=hcd2ec93_0
  - libcudss=0.6.0.5=hcd2ec93_0
  - libcufft=11.4.1.4=h5888daf_0
  - libcufile=1.14.1.1=ha8da6e3_0
  - libcups=2.3.3=hb8b1518_5
  - libcurand=10.3.10.19=h9ab20c4_0
  - libcurl=8.14.1=h332b0f4_0
  - libcusolver=11.7.5.82=h9ab20c4_1
  - libcusparse=12.5.10.65=h5888daf_1
  - libde265=1.0.15=h00ab1b0_0
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.125=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libflac=1.4.3=h59595ed_0
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_3
  - libgcc-ng=15.1.0=h69a702a_3
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgettextpo=0.25.1=h5888daf_0
  - libgettextpo-devel=0.25.1=h5888daf_0
  - libgfortran=15.1.0=h69a702a_3
  - libgfortran5=15.1.0=hcea5267_3
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.2=h3618099_0
  - libglu=9.0.3=h5888daf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgoogle-cloud=2.36.0=hc4361e1_1
  - libgoogle-cloud-storage=2.36.0=h0121fbd_1
  - libgpg-error=1.55=h3f2d84a_0
  - libgrpc=1.71.0=h8e591d7_1
  - libheif=1.19.7=gpl_hc18d805_100
  - libhwloc=2.11.2=default_h3d81e11_1002
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=32_hc41d3b0_mkl
  - liblapacke=3.9.0=32_hbc6e62b_mkl
  - libllvm20=20.1.8=hecd9e04_0
  - liblzma=5.8.1=hb9d3cd8_2
  - libmagma=2.9.0=h19665d7_1
  - libmpdec=4.0.0=hb9d3cd8_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libnl=3.11.0=hb9d3cd8_0
  - libntlm=1.8=hb9d3cd8_0
  - libnvjitlink=12.9.86=h5888daf_1
  - libogg=1.3.5=hd0c01bc_1
  - libopencv=4.12.0=qt6_py313he3db276_600
  - libopengl=1.7.0=ha4b6fd6_2
  - libopentelemetry-cpp=1.21.0=hd1b1c89_0
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_0
  - libopenvino=2025.0.0=hdc3f47d_3
  - libopenvino-auto-batch-plugin=2025.0.0=h4d9b6c2_3
  - libopenvino-auto-plugin=2025.0.0=h4d9b6c2_3
  - libopenvino-hetero-plugin=2025.0.0=h981d57b_3
  - libopenvino-intel-cpu-plugin=2025.0.0=hdc3f47d_3
  - libopenvino-intel-gpu-plugin=2025.0.0=hdc3f47d_3
  - libopenvino-intel-npu-plugin=2025.0.0=hdc3f47d_3
  - libopenvino-ir-frontend=2025.0.0=h981d57b_3
  - libopenvino-onnx-frontend=2025.0.0=h0e684df_3
  - libopenvino-paddle-frontend=2025.0.0=h0e684df_3
  - libopenvino-pytorch-frontend=2025.0.0=h5888daf_3
  - libopenvino-tensorflow-frontend=2025.0.0=h684f15b_3
  - libopenvino-tensorflow-lite-frontend=2025.0.0=h5888daf_3
  - libopus=1.5.2=hd0c01bc_0
  - libparquet=20.0.0=h3f30f2e_8_cuda
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h943b412_0
  - libpq=17.5=h27ae623_0
  - libprotobuf=5.29.3=h501fc15_1
  - libre2-11=2025.06.26=hba17884_0
  - librsvg=2.58.4=he92a37e_3
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.50.2=hee844dc_2
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_3
  - libstdcxx-ng=15.1.0=h4852527_3
  - libsystemd0=257.7=h4e0b6ca_0
  - libthrift=0.21.0=h0e7cc3e_0
  - libtiff=4.7.0=hf01ce69_5
  - libtorch=2.7.1=cpu_mkl_h783a78b_102
  - libudev1=257.7=hbe16f8c_0
  - libunwind=1.8.2=h1441ba7_0
  - liburing=2.11=h84d6215_0
  - libusb=1.0.29=h73b1eb8_0
  - libutf8proc=2.10.0=h202a827_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.51.0=hb9d3cd8_0
  - libva=2.22.0=h4f16b4b_2
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.14.1=hac33072_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.10.0=h65c71a3_0
  - libxml2=2.13.8=h4bc477f_0
  - libxslt=1.1.39=h76b75d6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=20.1.8=h4922eb0_0
  - llvmlite=0.44.0=py313h1b76d92_1
  - lz4-c=1.10.0=h5888daf_1
  - markupsafe=3.0.2=py313h8060acc_1
  - matplotlib=3.10.3=py313h78bf25f_0
  - matplotlib-base=3.10.3=py313h129903b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mkl=2024.2.2=ha957f24_16
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpg123=1.32.9=hc50e24c_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - nccl=2.27.6.1=h49b9d9a_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.5=pyhe01879c_0
  - nlohmann_json=3.12.0=h3f2d84a_0
  - numba=0.61.2=py313h50b8c88_1
  - numpy=2.2.6=py313h17eae1a_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - opencv=4.12.0=qt6_py313h71e9f19_600
  - openexr=3.3.4=h2cd1444_0
  - openh264=2.6.0=hc22cd8d_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openldap=2.6.10=he970967_0
  - openssl=3.5.1=h7b32b05_0
  - optree=0.16.0=py313h33d0bda_0
  - orc=2.1.2=h17f744e_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.1=py313h08cd8bf_0
  - pango=1.56.4=hadf4263_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pcre2=10.45=hc749103_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py313h8db990d_0
  - pip=25.1.1=pyh145f28c_0
  - pixman=0.46.2=h29eaf8c_0
  - pkg-config=0.29.2=h4bc722e_1009
  - platformdirs=4.3.8=pyhe01879c_0
  - prometheus-cpp=1.3.0=ha5d0236_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py313h536fd9c_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pugixml=1.15=h3f63f65_0
  - pulseaudio-client=17.0=hac146a9_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-opencv=4.12.0=qt6_py313hc7b4929_600
  - pyarrow=20.0.0=py313h78bf25f_0
  - pyarrow-core=20.0.0=py313hc6b0d6e_0_cuda
  - pybind11=3.0.0=pyh9380348_1
  - pybind11-global=3.0.0=pyhf748d72_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyside6=6.9.1=py313h7dabd7a_0
  - python=3.13.5=hec9711d_102_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.13=7_cp313
  - pytorch=2.7.1=cpu_mkl_py313_he78a34b_102
  - pytz=2025.2=pyhd8ed1ab_0
  - pyzmq=27.0.0=py313h8e95178_0
  - qhull=2020.2=h434a139_5
  - qt6-main=6.9.1=h0384650_1
  - rav1e=0.7.1=h8fae777_3
  - rdma-core=58.0=h5888daf_0
  - re2=2025.06.26=h9925aae_0
  - readline=8.2=h8c095d6_2
  - s2n=1.5.22=h96f233e_0
  - scikit-learn=1.7.0=py313h8ef605b_1
  - scipy=1.16.0=py313h86fcf2b_0
  - sdl2=2.32.54=h3f2d84a_0
  - sdl3=3.2.18=h68140b3_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - sleef=3.8=h1b44611_0
  - snappy=1.2.2=h03e3b7b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - svt-av1=3.0.2=h5888daf_0
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2021.13.0=hceb3a55_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_hd72426e_102
  - torchvision=0.22.0=cpu_py313_h4d12d60_1
  - torchvision-extra-decoders=0.0.2=py313hf1e760e_3
  - tornado=6.5.1=py313h536fd9c_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - triton=3.3.1=cuda129py313h246eb7c_2
  - typing-extensions=4.14.1=h4440ef1_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025b=h78e105d_0
  - wayland=1.24.0=h3e06ad9_0
  - wayland-protocols=1.45=hd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xarray=2025.7.1=pyhd8ed1ab_0
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.45=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxscrnsaver=1.2.4=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - assertpy==1.1
      - fastargs==1.2.0
      - ffcv==1.0.2
      - pytorch-pfn-extras==0.8.3
      - src==0.0.0
      - terminaltables==3.1.10
      - tqdm==4.67.1
prefix: /opt/conda/envs/ioncast
