name: ioncast-physicsnemo-halil
channels:
  - pytorch
  - dglteam/label/th24_cu124
  - anaconda
  - nvidia
  - nvidia/label/cuda-12.4.0
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.14=hb9d3cd8_0
  - aom=3.9.1=hac33072_0
  - attr=2.5.1=h166bdaf_1
  - binutils=2.44=h4852527_1
  - binutils_impl_linux-64=2.44=h4bf12b8_1
  - binutils_linux-64=2.44=h4852527_1
  - brotli=1.1.0=hb9d3cd8_3
  - brotli-bin=1.1.0=hb9d3cd8_3
  - brotli-python=1.1.0=py312h2ec8cdc_3
  - bzip2=1.0.8=h4bc722e_7
  - c-compiler=1.11.0=h4d9bdce_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py312h06ac9bb_0
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - conda-gcc-specs=14.3.0=hb991d5c_4
  - contourpy=1.3.3=py312hd9148b4_1
  - cpython=3.12.11=py312hd8ed1ab_0
  - cuda-cccl=12.4.99=0
  - cuda-command-line-tools=12.4.0=0
  - cuda-compiler=12.4.0=hbad6d8a_0
  - cuda-cudart=12.4.127=0
  - cuda-cudart-dev=12.4.99=0
  - cuda-cudart-static=12.9.79=h5888daf_0
  - cuda-cudart-static_linux-64=12.9.79=h3f2d84a_0
  - cuda-cuobjdump=12.4.99=0
  - cuda-cupti=12.4.127=0
  - cuda-cuxxfilt=12.4.99=0
  - cuda-documentation=12.4.99=0
  - cuda-driver-dev=12.4.99=0
  - cuda-gdb=12.9.79=ha677faa_0
  - cuda-libraries=12.4.1=0
  - cuda-libraries-dev=12.4.0=ha770c72_0
  - cuda-libraries-static=12.9.1=ha770c72_0
  - cuda-nsight=12.9.79=h7938cbb_0
  - cuda-nsight-compute=12.4.0=0
  - cuda-nvcc=12.4.99=0
  - cuda-nvdisasm=12.9.88=hbd13f7d_0
  - cuda-nvml-dev=12.9.79=hbd13f7d_0
  - cuda-nvprof=12.9.79=hcf8d014_0
  - cuda-nvprune=12.4.99=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvrtc-dev=12.4.99=0
  - cuda-nvrtc-static=12.9.86=h5888daf_0
  - cuda-nvtx=12.4.127=0
  - cuda-nvvp=12.9.79=hbd13f7d_0
  - cuda-opencl=12.9.19=0
  - cuda-opencl-dev=12.4.99=0
  - cuda-profiler-api=12.4.99=0
  - cuda-runtime=12.4.1=0
  - cuda-sanitizer-api=12.9.79=hcf8d014_0
  - cuda-toolkit=12.4.0=0
  - cuda-tools=12.4.0=ha770c72_0
  - cuda-version=12.9=3
  - cuda-visual-tools=12.4.0=0
  - cudnn=9.1.1.17=cuda12_1
  - cxx-compiler=1.11.0=hfcd1e18_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h3c4dab8_0
  - dgl=2.4.0.th24.cu124=py312_0
  - ffmpeg=7.1.0=gpl_heed6883_705
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.59.0=py312h8a5da7c_0
  - freetype=2.13.3=ha770c72_1
  - fribidi=1.0.10=h36c2ea0_0
  - fsspec=2025.7.0=pyhd8ed1ab_0
  - gcc=14.3.0=h76bdaa0_4
  - gcc_impl_linux-64=14.3.0=hd9e9e21_4
  - gcc_linux-64=14.3.0=h1382650_11
  - gdk-pixbuf=2.42.12=h7b179bb_1
  - gds-tools=1.9.0.20=0
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - glib=2.84.3=h89d24bf_0
  - glib-tools=2.84.3=hf516916_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py312h7201bc8_0
  - graphite2=1.3.14=hecca717_1
  - gst-plugins-base=1.24.11=h651a532_0
  - gstreamer=1.24.11=hc37bda9_0
  - gxx=14.3.0=he448592_4
  - gxx_impl_linux-64=14.3.0=he663afc_4
  - gxx_linux-64=14.3.0=ha7acb78_11
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=11.3.3=hbb57e21_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - joblib=1.5.1=pyhd8ed1ab_0
  - kernel-headers_linux-64=4.18.0=he073ed8_8
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.8=py312h68727a3_1
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h1423503_1
  - lerc=4.0.0=h0aef613_1
  - libabseil=20240116.2=cxx17_he02047a_1
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libass=0.17.3=h52826cd_2
  - libblas=3.9.0=32_h59b9bed_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_3
  - libbrotlidec=1.1.0=hb9d3cd8_3
  - libbrotlienc=1.1.0=hb9d3cd8_3
  - libcap=2.75=h39aace5_0
  - libcblas=3.9.0=32_he106b2a_openblas
  - libclang-cpp20.1=20.1.8=default_hddf928d_0
  - libclang13=20.1.8=default_ha444ac7_0
  - libcublas=12.4.5.8=0
  - libcublas-dev=12.4.2.65=0
  - libcublas-static=12.9.1.4=h9ab20c4_0
  - libcufft=11.2.1.3=0
  - libcufft-dev=11.2.0.44=0
  - libcufft-static=11.4.1.4=h5888daf_0
  - libcufile=1.14.1.1=4
  - libcufile-dev=1.9.0.20=0
  - libcufile-static=1.14.1.1=h5888daf_0
  - libcups=2.3.3=hb8b1518_5
  - libcurand=10.3.10.19=0
  - libcurand-dev=10.3.5.119=0
  - libcurand-static=10.3.10.19=h9ab20c4_0
  - libcusolver=11.6.1.9=0
  - libcusolver-dev=11.6.0.99=0
  - libcusolver-static=11.7.5.82=h9ab20c4_1
  - libcusparse=12.3.1.170=0
  - libcusparse-dev=12.3.0.142=0
  - libcusparse-static=12.5.10.65=h5888daf_1
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.125=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libflac=1.4.3=h59595ed_0
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-devel_linux-64=14.3.0=h85bb3a7_104
  - libgcc-ng=15.1.0=h69a702a_4
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran=15.1.0=h69a702a_4
  - libgfortran5=15.1.0=hcea5267_4
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.3=hf39c6af_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.1.0=h767d61c_4
  - libgpg-error=1.55=h3f2d84a_0
  - libhwloc=2.12.1=default_h3d81e11_1000
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=32_h7ac8fdf_openblas
  - libllvm20=20.1.8=hecd9e04_0
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnpp=12.2.5.30=0
  - libnpp-dev=12.2.5.2=0
  - libnpp-static=12.4.1.87=h9ab20c4_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libnvfatbin=12.9.82=0
  - libnvfatbin-dev=12.4.99=0
  - libnvfatbin-static=12.9.82=h5888daf_0
  - libnvjitlink=12.4.127=0
  - libnvjitlink-dev=12.4.99=0
  - libnvjitlink-static=12.9.86=h5888daf_1
  - libnvjpeg=12.3.1.117=0
  - libnvjpeg-dev=12.3.1.89=0
  - libnvjpeg-static=12.4.0.76=ha770c72_0
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.30=pthreads_h94d23a6_1
  - libopengl=1.7.0=ha4b6fd6_2
  - libopenvino=2024.4.0=hac27bb2_0
  - libopenvino-auto-batch-plugin=2024.4.0=h4d9b6c2_0
  - libopenvino-auto-plugin=2024.4.0=h4d9b6c2_0
  - libopenvino-hetero-plugin=2024.4.0=h3f63f65_0
  - libopenvino-intel-cpu-plugin=2024.4.0=hac27bb2_0
  - libopenvino-intel-gpu-plugin=2024.4.0=hac27bb2_0
  - libopenvino-intel-npu-plugin=2024.4.0=hac27bb2_0
  - libopenvino-ir-frontend=2024.4.0=h3f63f65_0
  - libopenvino-onnx-frontend=2024.4.0=h56242b0_0
  - libopenvino-paddle-frontend=2024.4.0=h56242b0_0
  - libopenvino-pytorch-frontend=2024.4.0=h5888daf_0
  - libopenvino-tensorflow-frontend=2024.4.0=h358ae18_0
  - libopenvino-tensorflow-lite-frontend=2024.4.0=h5888daf_0
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - libpq=17.5=h27ae623_0
  - libprotobuf=4.25.3=hd5b35b9_1
  - librsvg=2.58.4=he92a37e_3
  - libsanitizer=14.3.0=hd08acf3_4
  - libsndfile=1.2.2=hc60ed4a_1
  - libsqlite=3.50.4=h0c1763c_0
  - libstdcxx=15.1.0=h8f9b012_4
  - libstdcxx-devel_linux-64=14.3.0=h85bb3a7_104
  - libstdcxx-ng=15.1.0=h4852527_4
  - libsystemd0=257.7=h4e0b6ca_0
  - libtiff=4.7.0=hf01ce69_5
  - libtorch=2.4.0=cpu_generic_h4a3044c_1
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.51.0=hb03c661_1
  - libva=2.22.0=h4f16b4b_2
  - libvorbis=1.3.7=h54a6638_2
  - libvpx=1.14.1=hac33072_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.10.0=h65c71a3_0
  - libxkbfile=1.1.0=h166bdaf_1
  - libxml2=2.13.8=h04c0eec_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - matplotlib=3.10.0=py312h06a4308_0
  - matplotlib-base=3.10.0=py312hd3ec401_0
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpg123=1.32.9=hc50e24c_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - networkx=3.5=pyhe01879c_0
  - nomkl=1.0=h5ca1d4c_0
  - nsight-compute=2025.2.1.3=hb5ebaad_0
  - nspr=4.37=h29cc59b_0
  - nss=3.114=hc3c8bcf_0
  - numpy=2.3.2=py312h33ff503_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openh264=2.5.0=hf92e6e3_0
  - openjpeg=2.5.3=h55fea9a_1
  - openldap=2.6.10=he970967_0
  - openssl=3.5.1=h7b32b05_0
  - pandas=2.3.1=py312hf79963d_0
  - pango=1.56.4=hadf4263_0
  - pcre2=10.45=hc749103_0
  - pillow=11.3.0=py312h80c1187_0
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h537e5f6_0
  - ply=3.11=pyhd8ed1ab_3
  - psutil=7.0.0=py312h66e93f0_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pugixml=1.14=h59595ed_0
  - pulseaudio-client=17.0=hac146a9_1
  - pycparser=2.22=pyh29332c3_1
  - pyparsing=3.2.3=pyhe01879c_2
  - pyqt=5.15.11=py312hcec5e1c_0
  - pyqt5-sip=12.17.0=py312h2ec8cdc_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.11=h9e4cc4f_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=h434a139_5
  - qt-main=5.15.15=hea1682b_4
  - readline=8.2=h8c095d6_2
  - requests=2.32.4=pyhd8ed1ab_0
  - scikit-learn=1.7.1=py312h4f0b9e3_0
  - scipy=1.16.0=py312hf734454_0
  - setuptools=80.9.0=pyhff2d567_0
  - sip=6.10.0=py312h2ec8cdc_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.8=h1b44611_0
  - snappy=1.2.2=h03e3b7b_0
  - svt-av1=2.3.0=h5888daf_0
  - sysroot_linux-64=2.28=h4ee821c_8
  - tbb=2022.2.0=hb60516a_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_hd72426e_102
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhe01879c_2
  - tornado=6.5.1=py312h66e93f0_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025b=h78e105d_0
  - unicodedata2=16.0.0=py312h66e93f0_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wayland=1.24.0=h3e06ad9_0
  - wayland-protocols=1.45=hd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.45=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxshmfence=1.3.3=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zstandard=0.23.0=py312h66e93f0_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.3.1
      - aiobotocore==2.23.2
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aioitertools==0.12.0
      - aiosignal==1.4.0
      - alembic==1.16.4
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.10.0
      - astunparse==1.6.3
      - attrs==25.3.0
      - black==22.10.0
      - blinker==1.9.0
      - boto3==1.39.8
      - botocore==1.39.8
      - braceexpand==0.1.7
      - bracex==2.6
      - cachetools==5.5.2
      - cartopy==0.25.0
      - cftime==1.6.4.post1
      - click==8.2.1
      - cloudpickle==3.1.1
      - coverage==6.5.0
      - crc32c==2.7.1
      - cryptography==45.0.5
      - databricks-sdk==0.61.0
      - decorator==5.2.1
      - dm-tree==0.1.9
      - docker==7.1.0
      - donfig==0.8.1.post1
      - einops==0.8.1
      - fastapi==0.116.1
      - filelock==3.13.1
      - flask==3.1.1
      - frozenlist==1.7.0
      - gast==0.6.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.40.3
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - greenlet==3.2.3
      - gunicorn==23.0.0
      - h11==0.16.0
      - h5py==3.14.0
      - hf-xet==1.1.5
      - huggingface-hub==0.34.3
      - hydra-core==1.3.2
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - iniconfig==2.1.0
      - interrogate==1.5.0
      - ioncast==0.0.0
      - itsdangerous==2.2.0
      - jaxtyping==0.3.2
      - jinja2==3.1.4
      - jmespath==1.0.1
      - jplephem==2.23
      - jsonschema==4.25.0
      - jsonschema-specifications==2025.4.1
      - lark==1.2.2
      - lazy-loader==0.4
      - mako==1.3.10
      - markupsafe==2.1.5
      - mlflow==3.2.0
      - mlflow-skinny==3.2.0
      - mlflow-tracing==3.2.0
      - moto==5.1.9
      - moviepy==2.2.1
      - multi-storage-client==0.25.0
      - multidict==6.6.3
      - mypy-extensions==1.1.0
      - netcdf4==1.7.2
      - numcodecs==0.16.1
      - nvidia-cublas-cu12==12.4.2.65
      - nvidia-cuda-cupti-cu12==12.4.99
      - nvidia-cuda-nvrtc-cu12==12.4.99
      - nvidia-cuda-runtime-cu12==12.4.99
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.0.44
      - nvidia-curand-cu12==10.3.5.119
      - nvidia-cusolver-cu12==11.6.0.99
      - nvidia-cusparse-cu12==12.3.0.142
      - nvidia-dali-cuda120==1.50.0
      - nvidia-ml-py==12.575.51
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvcomp-cu12==4.2.0.14
      - nvidia-nvimgcodec-cu12==0.5.0.13
      - nvidia-nvjitlink-cu12==12.4.99
      - nvidia-nvjpeg-cu12==12.4.0.76
      - nvidia-nvjpeg2k-cu12==0.8.1.40
      - nvidia-nvtiff-cu12==0.5.0.67
      - nvidia-nvtx-cu12==12.4.99
      - nvidia-physicsnemo==1.1.1
      - nvitop==1.5.2
      - nvtx==0.2.13
      - omegaconf==2.3.0
      - onnx==1.18.0
      - opentelemetry-api==1.36.0
      - opentelemetry-sdk==1.36.0
      - opentelemetry-semantic-conventions==0.57b0
      - packaging==24.2
      - pathspec==0.12.1
      - platformdirs==4.3.8
      - pluggy==1.6.0
      - pooch==1.8.2
      - proglog==0.1.12
      - propcache==0.3.2
      - protobuf==6.31.1
      - py==1.11.0
      - py-partiql-parser==0.6.1
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygments==2.19.2
      - pyproj==3.7.1
      - pyshp==2.3.1
      - pyspng==0.1.3
      - pytest==8.4.1
      - python-dotenv==1.1.1
      - pyvista==0.45.3
      - pyyaml==6.0.2
      - referencing==0.36.2
      - responses==0.25.7
      - rpds-py==0.26.0
      - rsa==4.9.1
      - ruamel-yaml==0.18.14
      - ruamel-yaml-clib==0.2.12
      - ruff==0.0.290
      - s3fs==2025.7.0
      - s3transfer==0.13.1
      - safetensors==0.5.3
      - scikit-image==0.25.2
      - scooby==0.10.1
      - sentry-sdk==2.34.1
      - sgp4==2.25
      - shapely==2.1.1
      - skyfield==1.53
      - smmap==5.0.2
      - sniffio==1.3.1
      - sqlalchemy==2.0.42
      - sqlparse==0.5.3
      - starlette==0.47.2
      - sympy==1.13.3
      - tabulate==0.9.0
      - tensorly==0.9.0
      - tensorly-torch==0.5.0
      - termcolor==3.1.0
      - tifffile==2025.6.11
      - timm==1.0.19
      - torch==2.4.0+cu124
      - torch-harmonics==0.6.5
      - torch-scatter==2.1.2
      - torchaudio==2.4.0+cu124
      - torchinfo==1.8.0
      - torchvision==0.19.0+cu124
      - transformer-engine==2.5.0
      - transformer-engine-cu12==2.5.0
      - transformer-engine-torch==2.5.0
      - treelib==1.8.0
      - triton==3.0.0
      - typing-extensions==4.12.2
      - typing-inspection==0.4.1
      - uvicorn==0.35.0
      - vtk==9.4.2
      - wadler-lindig==0.1.7
      - wandb==0.21.0
      - warp-lang==1.8.1
      - wcmatch==10.1
      - webdataset==1.0.2
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xarray==2025.7.1
      - xattr==1.1.4
      - xmltodict==0.14.2
      - yarl==1.20.1
      - zarr==3.1.1
      - zipp==3.23.0
prefix: /home/hert7450/miniforge3/envs/ioncast-physicsnemo-halil
