wandb_version: 1

area_weighted_loss:
  value: false
aux_weight:
  value: 0.2
batch_size:
  value: 8
context_window:
  value: 24
date_dilation:
  value: 5
delta_minutes:
  value: 15
dropout:
  value: 0.1
epochs:
  value: 2
jpld_weight:
  value: 2
learning_rate:
  value: 1.835333885765676e-05
n_harmonics:
  value: 10
n_sunlocked_heads:
  value: 180
num_workers:
  value: 2
prediction_window:
  value: 8
sfno_depth:
  value: 8
sfno_modes_lat:
  value: 24
sfno_modes_lon:
  value: 96
sfno_width:
  value: 96
spectral_backend:
  value: rfft
weight_decay:
  value: 1.0e-06
