wandb_version: 1

area_weighted_loss:
  value: false
aux_weight:
  value: 0.2
batch_size:
  value: 8
context_window:
  value: 24
date_dilation:
  value: 1
delta_minutes:
  value: 360
dropout:
  value: 0.1
epochs:
  value: 2
jpld_weight:
  value: 0.8
learning_rate:
  value: 0.00011723166912644258
n_harmonics:
  value: 6
n_sunlocked_heads:
  value: 360
prediction_window:
  value: 1
sfno_depth:
  value: 12
sfno_modes_lat:
  value: 48
sfno_modes_lon:
  value: 48
sfno_width:
  value: 96
spectral_backend:
  value: sht
weight_decay:
  value: 0.0001
