wandb_version: 1

area_weighted_loss:
  value: false
aux_weight:
  value: 0.2
batch_size:
  value: 16
context_window:
  value: 12
date_dilation:
  value: 50
delta_minutes:
  value: 180
dropout:
  value: 0.15
epochs:
  value: 4
jpld_weight:
  value: 2
learning_rate:
  value: 0.00010774134561116546
n_harmonics:
  value: 1
n_sunlocked_heads:
  value: 180
prediction_window:
  value: 8
sfno_depth:
  value: 12
sfno_modes_lat:
  value: 48
sfno_modes_lon:
  value: 96
sfno_width:
  value: 96
spectral_backend:
  value: rfft
weight_decay:
  value: 1.0e-06
