wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.1
batch_size:
  value: 4
context_window:
  value: 1
date_dilation:
  value: 1
delta_minutes:
  value: 60
dropout:
  value: 0.2
epochs:
  value: 4
jpld_weight:
  value: 1
learning_rate:
  value: 0.00015954142246943194
n_harmonics:
  value: 10
n_sunlocked_heads:
  value: 180
prediction_window:
  value: 8
sfno_depth:
  value: 6
sfno_modes_lat:
  value: 24
sfno_modes_lon:
  value: 48
sfno_width:
  value: 128
spectral_backend:
  value: rfft
weight_decay:
  value: 0.0001
