wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.1
batch_size:
  value: 8
context_window:
  value: 24
date_dilation:
  value: 10
delta_minutes:
  value: 360
dropout:
  value: 0.3
epochs:
  value: 2
jpld_weight:
  value: 2
learning_rate:
  value: 0.00048081255535378537
n_harmonics:
  value: 8
n_sunlocked_heads:
  value: 360
prediction_window:
  value: 16
sfno_depth:
  value: 8
sfno_modes_lat:
  value: 48
sfno_modes_lon:
  value: 48
sfno_width:
  value: 96
spectral_backend:
  value: sht
weight_decay:
  value: 1.0e-06
