wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.5
batch_size:
  value: 2
context_window:
  value: 12
date_dilation:
  value: 10
delta_minutes:
  value: 60
dropout:
  value: 0.3
epochs:
  value: 6
jpld_weight:
  value: 0.8
learning_rate:
  value: 0.0006353367338111735
n_harmonics:
  value: 6
n_sunlocked_heads:
  value: 360
prediction_window:
  value: 16
sfno_depth:
  value: 10
sfno_modes_lat:
  value: 48
sfno_modes_lon:
  value: 48
sfno_width:
  value: 128
spectral_backend:
  value: sht
weight_decay:
  value: 1.0e-05
