wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.5
batch_size:
  value: 16
context_window:
  value: 1
date_dilation:
  value: 10
delta_minutes:
  value: 60
dropout:
  value: 0.3
epochs:
  value: 6
jpld_weight:
  value: 2
learning_rate:
  value: 0.0001147207003328233
n_harmonics:
  value: 2
n_sunlocked_heads:
  value: 180
prediction_window:
  value: 4
sfno_depth:
  value: 12
sfno_modes_lat:
  value: 48
sfno_modes_lon:
  value: 96
sfno_width:
  value: 48
spectral_backend:
  value: sht
weight_decay:
  value: 0
