wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.1
batch_size:
  value: 8
context_window:
  value: 12
date_dilation:
  value: 20
delta_minutes:
  value: 60
dropout:
  value: 0.1
epochs:
  value: 20
jpld_weight:
  value: 1
learning_rate:
  value: 6.644209278250919e-05
n_harmonics:
  value: 1
n_sunlocked_heads:
  value: 360
num_workers:
  value: 1
prediction_window:
  value: 1
sfno_depth:
  value: 6
sfno_modes_lat:
  value: 48
sfno_modes_lon:
  value: 64
sfno_width:
  value: 128
spectral_backend:
  value: sht
weight_decay:
  value: 0.0001
