wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.1
batch_size:
  value: 2
context_window:
  value: 24
date_dilation:
  value: 10
dropout:
  value: 0.3
epochs:
  value: 2
jpld_weight:
  value: 2
learning_rate:
  value: 2.568751042394445e-05
n_harmonics:
  value: 3
n_sunlocked_heads:
  value: 360
prediction_window:
  value: 1
sfno_depth:
  value: 10
sfno_modes_lat:
  value: 48
sfno_modes_lon:
  value: 64
sfno_width:
  value: 48
spectral_backend:
  value: sht
weight_decay:
  value: 0.0001
