wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.5
batch_size:
  value: 2
context_window:
  value: 8
date_dilation:
  value: 50
dropout:
  value: 0.1
epochs:
  value: 6
jpld_weight:
  value: 2
learning_rate:
  value: 0.0009269822871535031
n_harmonics:
  value: 2
n_sunlocked_heads:
  value: 360
prediction_window:
  value: 1
sfno_depth:
  value: 10
sfno_modes_lat:
  value: 48
sfno_modes_lon:
  value: 64
sfno_width:
  value: 64
spectral_backend:
  value: rfft
weight_decay:
  value: 0.0001
