wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.5
batch_size:
  value: 1
context_window:
  value: 12
date_dilation:
  value: 10
dropout:
  value: 0.2
epochs:
  value: 4
jpld_weight:
  value: 2
learning_rate:
  value: 1.4740878037332768e-05
n_harmonics:
  value: 10
n_sunlocked_heads:
  value: 180
prediction_window:
  value: 16
sfno_depth:
  value: 12
sfno_modes_lat:
  value: 24
sfno_modes_lon:
  value: 96
sfno_width:
  value: 48
spectral_backend:
  value: sht
weight_decay:
  value: 0
