wandb_version: 1

area_weighted_loss:
  value: false
aux_weight:
  value: 0.1
batch_size:
  value: 2
context_window:
  value: 8
date_dilation:
  value: 1
delta_minutes:
  value: 30
dropout:
  value: 0.3
epochs:
  value: 10
jpld_weight:
  value: 0.8
learning_rate:
  value: 8.597727150057199e-05
n_harmonics:
  value: 3
n_sunlocked_heads:
  value: 360
num_workers:
  value: 2
prediction_window:
  value: 2
sfno_depth:
  value: 6
sfno_modes_lat:
  value: 32
sfno_modes_lon:
  value: 96
sfno_width:
  value: 48
spectral_backend:
  value: rfft
weight_decay:
  value: 1.0e-06
