wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.1
batch_size:
  value: 1
context_window:
  value: 8
date_dilation:
  value: 5
delta_minutes:
  value: 15
dropout:
  value: 0.5
epochs:
  value: 10
jpld_weight:
  value: 1
learning_rate:
  value: 0.0017736557523520308
n_harmonics:
  value: 3
n_sunlocked_heads:
  value: 180
num_workers:
  value: 2
prediction_window:
  value: 2
sfno_depth:
  value: 8
sfno_modes_lat:
  value: 24
sfno_modes_lon:
  value: 96
sfno_width:
  value: 64
spectral_backend:
  value: rfft
weight_decay:
  value: 1.0e-05
