wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.1
batch_size:
  value: 2
context_window:
  value: 1
date_dilation:
  value: 5
delta_minutes:
  value: 15
dropout:
  value: 0.5
epochs:
  value: 10
jpld_weight:
  value: 0.8
learning_rate:
  value: 1.5922778135157055e-05
n_harmonics:
  value: 2
n_sunlocked_heads:
  value: 360
num_workers:
  value: 2
prediction_window:
  value: 1
sfno_depth:
  value: 10
sfno_modes_lat:
  value: 32
sfno_modes_lon:
  value: 48
sfno_width:
  value: 64
spectral_backend:
  value: rfft
weight_decay:
  value: 0
