wandb_version: 1

area_weighted_loss:
  value: false
aux_weight:
  value: 0.1
batch_size:
  value: 8
context_window:
  value: 12
date_dilation:
  value: 10
delta_minutes:
  value: 30
dropout:
  value: 0.3
epochs:
  value: 10
jpld_weight:
  value: 0.8
learning_rate:
  value: 0.001657762179307736
n_harmonics:
  value: 3
n_sunlocked_heads:
  value: 360
num_workers:
  value: 2
prediction_window:
  value: 1
sfno_depth:
  value: 10
sfno_modes_lat:
  value: 24
sfno_modes_lon:
  value: 96
sfno_width:
  value: 96
spectral_backend:
  value: rfft
weight_decay:
  value: 0.0001
