wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.2
batch_size:
  value: 2
context_window:
  value: 12
date_dilation:
  value: 10
delta_minutes:
  value: 15
dropout:
  value: 0.5
epochs:
  value: 10
jpld_weight:
  value: 1
learning_rate:
  value: 0.0013392890704900665
n_harmonics:
  value: 2
n_sunlocked_heads:
  value: 180
num_workers:
  value: 2
prediction_window:
  value: 2
sfno_depth:
  value: 10
sfno_modes_lat:
  value: 24
sfno_modes_lon:
  value: 96
sfno_width:
  value: 128
spectral_backend:
  value: rfft
weight_decay:
  value: 0
