wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.1
batch_size:
  value: 8
context_window:
  value: 1
date_dilation:
  value: 1
delta_minutes:
  value: 15
dropout:
  value: 0.3
epochs:
  value: 10
jpld_weight:
  value: 2
learning_rate:
  value: 0.0008767109125650885
n_harmonics:
  value: 6
n_sunlocked_heads:
  value: 180
num_workers:
  value: 2
prediction_window:
  value: 2
sfno_depth:
  value: 8
sfno_modes_lat:
  value: 32
sfno_modes_lon:
  value: 48
sfno_width:
  value: 48
spectral_backend:
  value: sht
weight_decay:
  value: 1.0e-05
