wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.1
batch_size:
  value: 1
context_window:
  value: 12
date_dilation:
  value: 5
delta_minutes:
  value: 15
dropout:
  value: 0.05
epochs:
  value: 10
jpld_weight:
  value: 1
learning_rate:
  value: 0.001776204452149368
n_harmonics:
  value: 8
n_sunlocked_heads:
  value: 180
num_workers:
  value: 2
prediction_window:
  value: 1
sfno_depth:
  value: 8
sfno_modes_lat:
  value: 48
sfno_modes_lon:
  value: 64
sfno_width:
  value: 48
spectral_backend:
  value: sht
weight_decay:
  value: 1.0e-06
