wandb_version: 1

area_weighted_loss:
  value: false
aux_weight:
  value: 0.1
batch_size:
  value: 2
context_window:
  value: 8
date_dilation:
  value: 5
delta_minutes:
  value: 30
dropout:
  value: 0.05
epochs:
  value: 10
jpld_weight:
  value: 0.8
learning_rate:
  value: 2.6040342857895915e-05
n_harmonics:
  value: 6
n_sunlocked_heads:
  value: 360
num_workers:
  value: 2
prediction_window:
  value: 1
sfno_depth:
  value: 8
sfno_modes_lat:
  value: 48
sfno_modes_lon:
  value: 48
sfno_width:
  value: 48
spectral_backend:
  value: sht
weight_decay:
  value: 0.0001
