wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.2
batch_size:
  value: 1
context_window:
  value: 1
date_dilation:
  value: 1
delta_minutes:
  value: 30
dropout:
  value: 0.1
epochs:
  value: 10
jpld_weight:
  value: 2
learning_rate:
  value: 0.0007839989126294884
n_harmonics:
  value: 3
n_sunlocked_heads:
  value: 360
num_workers:
  value: 2
prediction_window:
  value: 1
sfno_depth:
  value: 6
sfno_modes_lat:
  value: 48
sfno_modes_lon:
  value: 96
sfno_width:
  value: 48
spectral_backend:
  value: sht
weight_decay:
  value: 1.0e-06
