wandb_version: 1

area_weighted_loss:
  value: false
aux_weight:
  value: 0.2
batch_size:
  value: 2
context_window:
  value: 1
date_dilation:
  value: 10
delta_minutes:
  value: 30
dropout:
  value: 0.5
epochs:
  value: 10
jpld_weight:
  value: 1
learning_rate:
  value: 0.00023928511000983837
n_harmonics:
  value: 6
n_sunlocked_heads:
  value: 360
num_workers:
  value: 2
prediction_window:
  value: 1
sfno_depth:
  value: 6
sfno_modes_lat:
  value: 32
sfno_modes_lon:
  value: 96
sfno_width:
  value: 128
spectral_backend:
  value: rfft
weight_decay:
  value: 1.0e-06
