wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.1
batch_size:
  value: 8
context_window:
  value: 12
date_dilation:
  value: 5
delta_minutes:
  value: 15
dropout:
  value: 0.05
epochs:
  value: 10
jpld_weight:
  value: 2
learning_rate:
  value: 0.0008356367821209478
n_harmonics:
  value: 6
n_sunlocked_heads:
  value: 360
num_workers:
  value: 2
prediction_window:
  value: 2
sfno_depth:
  value: 6
sfno_modes_lat:
  value: 24
sfno_modes_lon:
  value: 64
sfno_width:
  value: 64
spectral_backend:
  value: sht
weight_decay:
  value: 0
