wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.1
batch_size:
  value: 1
context_window:
  value: 12
date_dilation:
  value: 5
delta_minutes:
  value: 15
dropout:
  value: 0.1
epochs:
  value: 10
jpld_weight:
  value: 0.8
learning_rate:
  value: 0.0005137377193796397
n_harmonics:
  value: 3
n_sunlocked_heads:
  value: 360
num_workers:
  value: 2
prediction_window:
  value: 1
sfno_depth:
  value: 6
sfno_modes_lat:
  value: 32
sfno_modes_lon:
  value: 96
sfno_width:
  value: 48
spectral_backend:
  value: sht
weight_decay:
  value: 1.0e-05
