wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.2
batch_size:
  value: 1
context_window:
  value: 1
date_dilation:
  value: 5
delta_minutes:
  value: 15
dropout:
  value: 0.3
epochs:
  value: 10
jpld_weight:
  value: 1
learning_rate:
  value: 0.00015426614931228914
n_harmonics:
  value: 6
n_sunlocked_heads:
  value: 180
num_workers:
  value: 2
prediction_window:
  value: 2
sfno_depth:
  value: 10
sfno_modes_lat:
  value: 24
sfno_modes_lon:
  value: 96
sfno_width:
  value: 96
spectral_backend:
  value: rfft
weight_decay:
  value: 1.0e-06
