wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.1
batch_size:
  value: 2
context_window:
  value: 12
date_dilation:
  value: 10
delta_minutes:
  value: 30
dropout:
  value: 0.1
epochs:
  value: 10
jpld_weight:
  value: 2
learning_rate:
  value: 0.0002174193155183393
n_harmonics:
  value: 8
n_sunlocked_heads:
  value: 360
num_workers:
  value: 2
prediction_window:
  value: 1
sfno_depth:
  value: 6
sfno_modes_lat:
  value: 48
sfno_modes_lon:
  value: 48
sfno_width:
  value: 48
spectral_backend:
  value: rfft
weight_decay:
  value: 0
