wandb_version: 1

area_weighted_loss:
  value: false
aux_weight:
  value: 0.2
batch_size:
  value: 2
context_window:
  value: 8
date_dilation:
  value: 6
delta_minutes:
  value: 30
dropout:
  value: 0.3
epochs:
  value: 4
head_blend_sigma:
  value: 2.5
head_smooth_reg:
  value: 0.0003
jpld_weight:
  value: 2
learning_rate:
  value: 0.0002042694229557832
lon_blur_sigma_deg:
  value: 3
lon_highfreq_kmin:
  value: 120
lon_highfreq_reg:
  value: 5.0e-06
lon_tv_reg:
  value: 5.0e-06
mc_dropout:
  value: false
n_harmonics:
  value: 1
n_sunlocked_heads:
  value: 360
num_workers:
  value: 8
prediction_window:
  value: 1
sfno_depth:
  value: 8
sfno_modes_lat:
  value: 32
sfno_modes_lon:
  value: 96
sfno_width:
  value: 64
spectral_backend:
  value: rfft
weight_decay:
  value: 3.658945726711485e-05
