wandb_version: 1

area_weighted_loss:
  value: false
aux_weight:
  value: 0.1
batch_size:
  value: 8
context_window:
  value: 8
date_dilation:
  value: 6
delta_minutes:
  value: 30
dropout:
  value: 0.1
epochs:
  value: 4
head_blend_sigma:
  value: 2.5
head_smooth_reg:
  value: 0
jpld_weight:
  value: 1
learning_rate:
  value: 7.684559475211575e-05
lon_blur_sigma_deg:
  value: 5
lon_highfreq_kmin:
  value: 72
lon_highfreq_reg:
  value: 0
lon_tv_reg:
  value: 2.0e-05
mc_dropout:
  value: false
n_harmonics:
  value: 2
n_sunlocked_heads:
  value: 180
num_workers:
  value: 4
prediction_window:
  value: 1
sfno_depth:
  value: 8
sfno_modes_lat:
  value: 32
sfno_modes_lon:
  value: 96
sfno_width:
  value: 80
spectral_backend:
  value: sht
weight_decay:
  value: 5.443132885779437e-08
