wandb_version: 1

area_weighted_loss:
  value: false
aux_weight:
  value: 0.3
batch_size:
  value: 8
context_window:
  value: 4
date_dilation:
  value: 8
delta_minutes:
  value: 15
dropout:
  value: 0.1
epochs:
  value: 4
head_blend_sigma:
  value: 1.5
head_smooth_reg:
  value: 0.0001
jpld_weight:
  value: 2
learning_rate:
  value: 0.00017252777922010788
lon_blur_sigma_deg:
  value: 5
lon_highfreq_kmin:
  value: 120
lon_highfreq_reg:
  value: 0
lon_tv_reg:
  value: 0
mc_dropout:
  value: true
n_harmonics:
  value: 2
n_sunlocked_heads:
  value: 180
num_workers:
  value: 4
prediction_window:
  value: 1
sfno_depth:
  value: 6
sfno_modes_lat:
  value: 32
sfno_modes_lon:
  value: 64
sfno_width:
  value: 64
spectral_backend:
  value: sht
weight_decay:
  value: 1.3091033911391624e-08
