wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.2
batch_size:
  value: 2
context_window:
  value: 6
date_dilation:
  value: 8
delta_minutes:
  value: 15
dropout:
  value: 0.1
epochs:
  value: 4
head_blend_sigma:
  value: 1.5
head_smooth_reg:
  value: 0
jpld_weight:
  value: 0.8
learning_rate:
  value: 3.305070348745822e-05
lon_blur_sigma_deg:
  value: 3
lon_highfreq_kmin:
  value: 96
lon_highfreq_reg:
  value: 1.0e-06
lon_tv_reg:
  value: 0
mc_dropout:
  value: true
n_harmonics:
  value: 1
n_sunlocked_heads:
  value: 360
num_workers:
  value: 8
prediction_window:
  value: 1
sfno_depth:
  value: 6
sfno_modes_lat:
  value: 32
sfno_modes_lon:
  value: 64
sfno_width:
  value: 64
spectral_backend:
  value: sht
weight_decay:
  value: 4.160158543991213e-05
