wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.3
batch_size:
  value: 8
context_window:
  value: 6
date_dilation:
  value: 12
delta_minutes:
  value: 15
dropout:
  value: 0.1
epochs:
  value: 3
head_blend_sigma:
  value: 2
head_smooth_reg:
  value: 0.0003
jpld_weight:
  value: 1
learning_rate:
  value: 0.0001855214851873991
lon_blur_sigma_deg:
  value: 3
lon_highfreq_kmin:
  value: 72
lon_highfreq_reg:
  value: 5.0e-06
lon_tv_reg:
  value: 2.0e-05
mc_dropout:
  value: true
n_harmonics:
  value: 2
n_sunlocked_heads:
  value: 180
num_workers:
  value: 4
prediction_window:
  value: 2
sfno_depth:
  value: 6
sfno_modes_lat:
  value: 48
sfno_modes_lon:
  value: 96
sfno_width:
  value: 80
spectral_backend:
  value: rfft
weight_decay:
  value: 1.6717683691213258e-06
