wandb_version: 1

area_weighted_loss:
  value: false
aux_weight:
  value: 0.3
batch_size:
  value: 2
context_window:
  value: 6
date_dilation:
  value: 6
delta_minutes:
  value: 15
dropout:
  value: 0.2
epochs:
  value: 4
head_blend_sigma:
  value: 2
head_smooth_reg:
  value: 0.0003
jpld_weight:
  value: 1
learning_rate:
  value: 0.00016736322805950977
lon_blur_sigma_deg:
  value: 3
lon_highfreq_kmin:
  value: 120
lon_highfreq_reg:
  value: 1.0e-06
lon_tv_reg:
  value: 2.0e-05
mc_dropout:
  value: false
n_harmonics:
  value: 2
n_sunlocked_heads:
  value: 360
num_workers:
  value: 4
prediction_window:
  value: 1
sfno_depth:
  value: 8
sfno_modes_lat:
  value: 32
sfno_modes_lon:
  value: 64
sfno_width:
  value: 64
spectral_backend:
  value: sht
weight_decay:
  value: 3.495698817395312e-07
