wandb_version: 1

area_weighted_loss:
  value: false
aux_weight:
  value: 0.1
batch_size:
  value: 8
context_window:
  value: 6
date_dilation:
  value: 12
delta_minutes:
  value: 15
dropout:
  value: 0.1
epochs:
  value: 3
head_blend_sigma:
  value: 1.5
head_smooth_reg:
  value: 0.0001
jpld_weight:
  value: 2
learning_rate:
  value: 0.00014640901545476687
lon_blur_sigma_deg:
  value: 0
lon_highfreq_kmin:
  value: 72
lon_highfreq_reg:
  value: 5.0e-06
lon_tv_reg:
  value: 2.0e-05
mc_dropout:
  value: false
n_harmonics:
  value: 1
n_sunlocked_heads:
  value: 180
num_workers:
  value: 8
prediction_window:
  value: 1
sfno_depth:
  value: 8
sfno_modes_lat:
  value: 48
sfno_modes_lon:
  value: 64
sfno_width:
  value: 64
spectral_backend:
  value: sht
weight_decay:
  value: 1.0140969423332357e-07
