wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.3
batch_size:
  value: 8
context_window:
  value: 4
date_dilation:
  value: 12
delta_minutes:
  value: 15
dropout:
  value: 0.3
epochs:
  value: 4
head_blend_sigma:
  value: 2
head_smooth_reg:
  value: 0
jpld_weight:
  value: 2
learning_rate:
  value: 1.0701246558243514e-05
lon_blur_sigma_deg:
  value: 3
lon_highfreq_kmin:
  value: 120
lon_highfreq_reg:
  value: 0
lon_tv_reg:
  value: 5.0e-06
mc_dropout:
  value: false
n_harmonics:
  value: 1
n_sunlocked_heads:
  value: 180
num_workers:
  value: 4
prediction_window:
  value: 2
sfno_depth:
  value: 6
sfno_modes_lat:
  value: 32
sfno_modes_lon:
  value: 64
sfno_width:
  value: 80
spectral_backend:
  value: rfft
weight_decay:
  value: 9.02667302325603e-08
