wandb_version: 1

area_weighted_loss:
  value: false
aux_weight:
  value: 0.1
batch_size:
  value: 4
context_window:
  value: 8
date_dilation:
  value: 6
delta_minutes:
  value: 15
dropout:
  value: 0.2
epochs:
  value: 3
head_blend_sigma:
  value: 2
head_smooth_reg:
  value: 0.0001
jpld_weight:
  value: 1
learning_rate:
  value: 2.4440304510233584e-05
lon_blur_sigma_deg:
  value: 3
lon_highfreq_kmin:
  value: 120
lon_highfreq_reg:
  value: 1.0e-06
lon_tv_reg:
  value: 0
mc_dropout:
  value: false
n_harmonics:
  value: 1
n_sunlocked_heads:
  value: 180
num_workers:
  value: 8
prediction_window:
  value: 2
sfno_depth:
  value: 8
sfno_modes_lat:
  value: 48
sfno_modes_lon:
  value: 96
sfno_width:
  value: 64
spectral_backend:
  value: sht
weight_decay:
  value: 4.2026131013361555e-08
