wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.3
batch_size:
  value: 2
context_window:
  value: 6
date_dilation:
  value: 8
delta_minutes:
  value: 30
dropout:
  value: 0.3
epochs:
  value: 3
head_blend_sigma:
  value: 1.5
head_smooth_reg:
  value: 0.0003
jpld_weight:
  value: 0.8
learning_rate:
  value: 0.00011428457116346884
lon_blur_sigma_deg:
  value: 3
lon_highfreq_kmin:
  value: 72
lon_highfreq_reg:
  value: 0
lon_tv_reg:
  value: 5.0e-06
mc_dropout:
  value: false
n_harmonics:
  value: 1
n_sunlocked_heads:
  value: 180
num_workers:
  value: 4
prediction_window:
  value: 2
sfno_depth:
  value: 8
sfno_modes_lat:
  value: 32
sfno_modes_lon:
  value: 96
sfno_width:
  value: 64
spectral_backend:
  value: sht
weight_decay:
  value: 1.984564222473967e-07
