wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.1
batch_size:
  value: 8
context_window:
  value: 4
date_dilation:
  value: 8
delta_minutes:
  value: 15
dropout:
  value: 0.1
epochs:
  value: 4
head_blend_sigma:
  value: 2.5
head_smooth_reg:
  value: 0
jpld_weight:
  value: 1
learning_rate:
  value: 0.00013495941830700658
lon_blur_sigma_deg:
  value: 0
lon_highfreq_kmin:
  value: 72
lon_highfreq_reg:
  value: 1.0e-06
lon_tv_reg:
  value: 0
mc_dropout:
  value: false
n_harmonics:
  value: 1
n_sunlocked_heads:
  value: 360
num_workers:
  value: 8
prediction_window:
  value: 1
sfno_depth:
  value: 8
sfno_modes_lat:
  value: 32
sfno_modes_lon:
  value: 96
sfno_width:
  value: 64
spectral_backend:
  value: sht
weight_decay:
  value: 8.195480471026252e-08
