wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.3
batch_size:
  value: 2
context_window:
  value: 4
date_dilation:
  value: 6
delta_minutes:
  value: 15
dropout:
  value: 0.1
epochs:
  value: 3
head_blend_sigma:
  value: 2.5
head_smooth_reg:
  value: 0.0003
jpld_weight:
  value: 1
learning_rate:
  value: 0.00013675448253853647
lon_blur_sigma_deg:
  value: 0
lon_highfreq_kmin:
  value: 72
lon_highfreq_reg:
  value: 0
lon_tv_reg:
  value: 0
mc_dropout:
  value: false
n_harmonics:
  value: 1
n_sunlocked_heads:
  value: 360
num_workers:
  value: 8
prediction_window:
  value: 1
sfno_depth:
  value: 6
sfno_modes_lat:
  value: 32
sfno_modes_lon:
  value: 64
sfno_width:
  value: 64
spectral_backend:
  value: sht
weight_decay:
  value: 1.338475048196365e-06
