wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.1
batch_size:
  value: 4
context_window:
  value: 4
date_dilation:
  value: 12
delta_minutes:
  value: 15
dropout:
  value: 0.3
epochs:
  value: 3
head_blend_sigma:
  value: 2
head_smooth_reg:
  value: 0.0003
jpld_weight:
  value: 1
learning_rate:
  value: 1.1441649643126895e-05
lon_blur_sigma_deg:
  value: 5
lon_highfreq_kmin:
  value: 96
lon_highfreq_reg:
  value: 0
lon_tv_reg:
  value: 0
mc_dropout:
  value: true
n_harmonics:
  value: 2
n_sunlocked_heads:
  value: 180
num_workers:
  value: 4
prediction_window:
  value: 1
sfno_depth:
  value: 6
sfno_modes_lat:
  value: 48
sfno_modes_lon:
  value: 64
sfno_width:
  value: 80
spectral_backend:
  value: rfft
weight_decay:
  value: 1.7991963304750376e-06
