wandb_version: 1

area_weighted_loss:
  value: false
aux_weight:
  value: 0.2
batch_size:
  value: 8
context_window:
  value: 4
date_dilation:
  value: 6
delta_minutes:
  value: 30
dropout:
  value: 0.1
epochs:
  value: 4
head_blend_sigma:
  value: 2
head_smooth_reg:
  value: 0.0001
jpld_weight:
  value: 1
learning_rate:
  value: 8.792987647552376e-05
lon_blur_sigma_deg:
  value: 5
lon_highfreq_kmin:
  value: 96
lon_highfreq_reg:
  value: 5.0e-06
lon_tv_reg:
  value: 2.0e-05
mc_dropout:
  value: true
n_harmonics:
  value: 2
n_sunlocked_heads:
  value: 180
num_workers:
  value: 8
prediction_window:
  value: 1
sfno_depth:
  value: 6
sfno_modes_lat:
  value: 32
sfno_modes_lon:
  value: 96
sfno_width:
  value: 80
spectral_backend:
  value: sht
weight_decay:
  value: 6.177842212272315e-07
