wandb_version: 1

area_weighted_loss:
  value: false
aux_weight:
  value: 0.3
batch_size:
  value: 8
context_window:
  value: 4
date_dilation:
  value: 8
delta_minutes:
  value: 30
dropout:
  value: 0.2
epochs:
  value: 3
head_blend_sigma:
  value: 2
head_smooth_reg:
  value: 0
jpld_weight:
  value: 2
learning_rate:
  value: 0.0002820367468452206
lon_blur_sigma_deg:
  value: 3
lon_highfreq_kmin:
  value: 72
lon_highfreq_reg:
  value: 5.0e-06
lon_tv_reg:
  value: 2.0e-05
mc_dropout:
  value: false
n_harmonics:
  value: 2
n_sunlocked_heads:
  value: 360
num_workers:
  value: 4
prediction_window:
  value: 1
sfno_depth:
  value: 6
sfno_modes_lat:
  value: 32
sfno_modes_lon:
  value: 96
sfno_width:
  value: 80
spectral_backend:
  value: sht
weight_decay:
  value: 5.541238721323061e-06
