wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.3
batch_size:
  value: 2
context_window:
  value: 8
date_dilation:
  value: 8
delta_minutes:
  value: 15
dropout:
  value: 0.1
epochs:
  value: 4
head_blend_sigma:
  value: 1.5
head_smooth_reg:
  value: 0
jpld_weight:
  value: 2
learning_rate:
  value: 0.00028989905535082487
lon_blur_sigma_deg:
  value: 0
lon_highfreq_kmin:
  value: 96
lon_highfreq_reg:
  value: 1.0e-06
lon_tv_reg:
  value: 2.0e-05
mc_dropout:
  value: false
n_harmonics:
  value: 2
n_sunlocked_heads:
  value: 360
num_workers:
  value: 8
prediction_window:
  value: 1
sfno_depth:
  value: 6
sfno_modes_lat:
  value: 32
sfno_modes_lon:
  value: 96
sfno_width:
  value: 80
spectral_backend:
  value: sht
weight_decay:
  value: 4.268211849082549e-05
