wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.1
batch_size:
  value: 8
context_window:
  value: 4
date_dilation:
  value: 12
delta_minutes:
  value: 30
dropout:
  value: 0.1
epochs:
  value: 4
head_blend_sigma:
  value: 2
head_smooth_reg:
  value: 0.0003
jpld_weight:
  value: 2
learning_rate:
  value: 0.000251082508648472
lon_blur_sigma_deg:
  value: 5
lon_highfreq_kmin:
  value: 72
lon_highfreq_reg:
  value: 5.0e-06
lon_tv_reg:
  value: 2.0e-05
mc_dropout:
  value: true
n_harmonics:
  value: 1
n_sunlocked_heads:
  value: 180
num_workers:
  value: 8
prediction_window:
  value: 2
sfno_depth:
  value: 8
sfno_modes_lat:
  value: 32
sfno_modes_lon:
  value: 64
sfno_width:
  value: 64
spectral_backend:
  value: rfft
weight_decay:
  value: 2.665289501235049e-08
