wandb_version: 1

area_weighted_loss:
  value: false
aux_weight:
  value: 0.2
batch_size:
  value: 2
context_window:
  value: 8
date_dilation:
  value: 12
delta_minutes:
  value: 15
dropout:
  value: 0.3
epochs:
  value: 3
head_blend_sigma:
  value: 2.5
head_smooth_reg:
  value: 0.0003
jpld_weight:
  value: 1
learning_rate:
  value: 1.907326152163369e-05
lon_blur_sigma_deg:
  value: 5
lon_highfreq_kmin:
  value: 72
lon_highfreq_reg:
  value: 5.0e-06
lon_tv_reg:
  value: 5.0e-06
mc_dropout:
  value: true
n_harmonics:
  value: 2
n_sunlocked_heads:
  value: 180
num_workers:
  value: 8
prediction_window:
  value: 2
sfno_depth:
  value: 8
sfno_modes_lat:
  value: 48
sfno_modes_lon:
  value: 64
sfno_width:
  value: 64
spectral_backend:
  value: rfft
weight_decay:
  value: 8.718671498830969e-07
