wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.3
batch_size:
  value: 2
context_window:
  value: 6
date_dilation:
  value: 6
delta_minutes:
  value: 15
dropout:
  value: 0.3
epochs:
  value: 3
head_blend_sigma:
  value: 1.5
head_smooth_reg:
  value: 0
jpld_weight:
  value: 1
learning_rate:
  value: 0.00024100520832221487
lon_blur_sigma_deg:
  value: 3
lon_highfreq_kmin:
  value: 120
lon_highfreq_reg:
  value: 1.0e-06
lon_tv_reg:
  value: 0
mc_dropout:
  value: false
n_harmonics:
  value: 1
n_sunlocked_heads:
  value: 180
num_workers:
  value: 8
prediction_window:
  value: 1
sfno_depth:
  value: 6
sfno_modes_lat:
  value: 32
sfno_modes_lon:
  value: 64
sfno_width:
  value: 80
spectral_backend:
  value: sht
weight_decay:
  value: 1.2284130231395481e-08
