wandb_version: 1

area_weighted_loss:
  value: false
aux_weight:
  value: 0.3
batch_size:
  value: 8
context_window:
  value: 4
date_dilation:
  value: 8
delta_minutes:
  value: 30
dropout:
  value: 0.1
epochs:
  value: 3
head_blend_sigma:
  value: 1.5
head_smooth_reg:
  value: 0
jpld_weight:
  value: 2
learning_rate:
  value: 0.00028868976747380485
lon_blur_sigma_deg:
  value: 3
lon_highfreq_kmin:
  value: 96
lon_highfreq_reg:
  value: 5.0e-06
lon_tv_reg:
  value: 0
mc_dropout:
  value: true
n_harmonics:
  value: 2
n_sunlocked_heads:
  value: 180
num_workers:
  value: 8
prediction_window:
  value: 1
sfno_depth:
  value: 8
sfno_modes_lat:
  value: 32
sfno_modes_lon:
  value: 96
sfno_width:
  value: 80
spectral_backend:
  value: sht
weight_decay:
  value: 5.6122925885498e-07
