wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.1
batch_size:
  value: 4
context_window:
  value: 12
date_dilation:
  value: 50
delta_minutes:
  value: 30
dropout:
  value: 0.1
epochs:
  value: 20
jpld_weight:
  value: 2
learning_rate:
  value: 0.0016440048267276745
n_harmonics:
  value: 3
n_sunlocked_heads:
  value: 360
num_workers:
  value: 0
prediction_window:
  value: 4
sfno_depth:
  value: 6
sfno_modes_lat:
  value: 48
sfno_modes_lon:
  value: 48
sfno_width:
  value: 96
spectral_backend:
  value: sht
weight_decay:
  value: 1.0e-05
