wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.1
batch_size:
  value: 8
context_window:
  value: 12
date_dilation:
  value: 1
delta_minutes:
  value: 30
dropout:
  value: 0.3
epochs:
  value: 20
jpld_weight:
  value: 2
learning_rate:
  value: 5.483383832648334e-05
n_harmonics:
  value: 1
n_sunlocked_heads:
  value: 180
num_workers:
  value: 1
prediction_window:
  value: 8
sfno_depth:
  value: 10
sfno_modes_lat:
  value: 48
sfno_modes_lon:
  value: 48
sfno_width:
  value: 96
spectral_backend:
  value: sht
weight_decay:
  value: 1.0e-06
