wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.1
batch_size:
  value: 8
context_window:
  value: 8
date_dilation:
  value: 20
delta_minutes:
  value: 30
dropout:
  value: 0.3
epochs:
  value: 20
jpld_weight:
  value: 2
learning_rate:
  value: 1.666864072843833e-05
n_harmonics:
  value: 6
n_sunlocked_heads:
  value: 360
num_workers:
  value: 1
prediction_window:
  value: 8
sfno_depth:
  value: 6
sfno_modes_lat:
  value: 48
sfno_modes_lon:
  value: 48
sfno_width:
  value: 48
spectral_backend:
  value: sht
weight_decay:
  value: 1.0e-05
