wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.2
batch_size:
  value: 1
context_window:
  value: 4
date_dilation:
  value: 1
delta_minutes:
  value: 30
dropout:
  value: 0.15
epochs:
  value: 2
jpld_weight:
  value: 2
learning_rate:
  value: 0.00038392933846790526
n_harmonics:
  value: 8
n_sunlocked_heads:
  value: 360
num_workers:
  value: 1
prediction_window:
  value: 1
sfno_depth:
  value: 8
sfno_modes_lat:
  value: 32
sfno_modes_lon:
  value: 48
sfno_width:
  value: 64
spectral_backend:
  value: sht
weight_decay:
  value: 0.0001
