wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.2
batch_size:
  value: 4
context_window:
  value: 4
date_dilation:
  value: 50
delta_minutes:
  value: 30
dropout:
  value: 0.1
epochs:
  value: 4
jpld_weight:
  value: 1
learning_rate:
  value: 0.0005694871680522863
n_harmonics:
  value: 2
n_sunlocked_heads:
  value: 360
num_workers:
  value: 2
prediction_window:
  value: 4
sfno_depth:
  value: 6
sfno_modes_lat:
  value: 32
sfno_modes_lon:
  value: 64
sfno_width:
  value: 128
spectral_backend:
  value: sht
weight_decay:
  value: 1.0e-06
