wandb_version: 1

area_weighted_loss:
  value: false
aux_weight:
  value: 0.3
batch_size:
  value: 1
context_window:
  value: 4
date_dilation:
  value: 10
delta_minutes:
  value: 30
dropout:
  value: 0.2
epochs:
  value: 2
jpld_weight:
  value: 1
learning_rate:
  value: 0.0017524093964412352
n_harmonics:
  value: 8
n_sunlocked_heads:
  value: 360
num_workers:
  value: 2
prediction_window:
  value: 1
sfno_depth:
  value: 10
sfno_modes_lat:
  value: 48
sfno_modes_lon:
  value: 48
sfno_width:
  value: 64
spectral_backend:
  value: sht
weight_decay:
  value: 1.0e-06
