wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.5
batch_size:
  value: 2
context_window:
  value: 4
date_dilation:
  value: 5
delta_minutes:
  value: 30
dropout:
  value: 0.2
epochs:
  value: 2
jpld_weight:
  value: 0.8
learning_rate:
  value: 0.000840956312554237
n_harmonics:
  value: 6
n_sunlocked_heads:
  value: 360
num_workers:
  value: 2
prediction_window:
  value: 1
sfno_depth:
  value: 10
sfno_modes_lat:
  value: 24
sfno_modes_lon:
  value: 64
sfno_width:
  value: 128
spectral_backend:
  value: sht
weight_decay:
  value: 1.0e-05
