wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.3
batch_size:
  value: 4
context_window:
  value: 12
date_dilation:
  value: 50
delta_minutes:
  value: 30
dropout:
  value: 0.3
epochs:
  value: 6
jpld_weight:
  value: 1
learning_rate:
  value: 0.0011153369735923337
n_harmonics:
  value: 1
n_sunlocked_heads:
  value: 360
num_workers:
  value: 2
prediction_window:
  value: 1
sfno_depth:
  value: 6
sfno_modes_lat:
  value: 32
sfno_modes_lon:
  value: 48
sfno_width:
  value: 96
spectral_backend:
  value: sht
weight_decay:
  value: 1.0e-05
