wandb_version: 1

area_weighted_loss:
  value: false
aux_weight:
  value: 0.2
batch_size:
  value: 2
context_window:
  value: 8
date_dilation:
  value: 5
delta_minutes:
  value: 15
dropout:
  value: 0.15
epochs:
  value: 2
jpld_weight:
  value: 2
learning_rate:
  value: 0.00022290376284311703
n_harmonics:
  value: 2
n_sunlocked_heads:
  value: 360
num_workers:
  value: 1
prediction_window:
  value: 1
sfno_depth:
  value: 8
sfno_modes_lat:
  value: 32
sfno_modes_lon:
  value: 48
sfno_width:
  value: 96
spectral_backend:
  value: sht
weight_decay:
  value: 1.0e-05
