wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.3
batch_size:
  value: 2
context_window:
  value: 4
date_dilation:
  value: 20
delta_minutes:
  value: 30
dropout:
  value: 0.3
epochs:
  value: 4
jpld_weight:
  value: 2
learning_rate:
  value: 1.1005592172408335e-05
n_harmonics:
  value: 3
n_sunlocked_heads:
  value: 360
num_workers:
  value: 2
prediction_window:
  value: 1
sfno_depth:
  value: 10
sfno_modes_lat:
  value: 24
sfno_modes_lon:
  value: 96
sfno_width:
  value: 128
spectral_backend:
  value: sht
weight_decay:
  value: 0.0001
