wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.1
batch_size:
  value: 2
context_window:
  value: 4
date_dilation:
  value: 1
delta_minutes:
  value: 30
dropout:
  value: 0.2
epochs:
  value: 2
jpld_weight:
  value: 0.8
learning_rate:
  value: 0.002042950487487906
n_harmonics:
  value: 2
n_sunlocked_heads:
  value: 360
num_workers:
  value: 1
prediction_window:
  value: 1
sfno_depth:
  value: 6
sfno_modes_lat:
  value: 32
sfno_modes_lon:
  value: 48
sfno_width:
  value: 64
spectral_backend:
  value: sht
weight_decay:
  value: 1.0e-05
