wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.2
batch_size:
  value: 1
context_window:
  value: 1
date_dilation:
  value: 1
delta_minutes:
  value: 30
dropout:
  value: 0.2
epochs:
  value: 6
jpld_weight:
  value: 2
learning_rate:
  value: 0.00017380989054789322
n_harmonics:
  value: 6
n_sunlocked_heads:
  value: 360
num_workers:
  value: 2
prediction_window:
  value: 4
sfno_depth:
  value: 12
sfno_modes_lat:
  value: 24
sfno_modes_lon:
  value: 64
sfno_width:
  value: 64
spectral_backend:
  value: sht
weight_decay:
  value: 1.0e-06
