wandb_version: 1

area_weighted_loss:
  value: false
aux_weight:
  value: 0.3
batch_size:
  value: 2
context_window:
  value: 8
date_dilation:
  value: 20
delta_minutes:
  value: 15
dropout:
  value: 0.15
epochs:
  value: 6
jpld_weight:
  value: 0.8
learning_rate:
  value: 0.0007452304337950364
n_harmonics:
  value: 3
n_sunlocked_heads:
  value: 360
num_workers:
  value: 1
prediction_window:
  value: 4
sfno_depth:
  value: 12
sfno_modes_lat:
  value: 48
sfno_modes_lon:
  value: 48
sfno_width:
  value: 96
spectral_backend:
  value: sht
weight_decay:
  value: 1.0e-05
