wandb_version: 1

area_weighted_loss:
  value: false
aux_weight:
  value: 0.1
batch_size:
  value: 1
context_window:
  value: 4
date_dilation:
  value: 10
delta_minutes:
  value: 15
dropout:
  value: 0.15
epochs:
  value: 4
jpld_weight:
  value: 1
learning_rate:
  value: 0.0007616413239114243
n_harmonics:
  value: 2
n_sunlocked_heads:
  value: 180
num_workers:
  value: 1
prediction_window:
  value: 1
sfno_depth:
  value: 10
sfno_modes_lat:
  value: 24
sfno_modes_lon:
  value: 48
sfno_width:
  value: 96
spectral_backend:
  value: sht
weight_decay:
  value: 1.0e-05
