wandb_version: 1

area_weighted_loss:
  value: false
aux_weight:
  value: 0.2
batch_size:
  value: 2
context_window:
  value: 8
date_dilation:
  value: 10
delta_minutes:
  value: 30
dropout:
  value: 0.3
epochs:
  value: 4
jpld_weight:
  value: 1
learning_rate:
  value: 0.001804256577504037
n_harmonics:
  value: 2
n_sunlocked_heads:
  value: 180
num_workers:
  value: 2
prediction_window:
  value: 1
sfno_depth:
  value: 8
sfno_modes_lat:
  value: 48
sfno_modes_lon:
  value: 48
sfno_width:
  value: 128
spectral_backend:
  value: sht
weight_decay:
  value: 1.0e-06
