wandb_version: 1

area_weighted_loss:
  value: false
aux_weight:
  value: 0.1
batch_size:
  value: 1
context_window:
  value: 4
date_dilation:
  value: 5
delta_minutes:
  value: 30
dropout:
  value: 0.1
epochs:
  value: 2
jpld_weight:
  value: 2
learning_rate:
  value: 0.0007649018208257646
n_harmonics:
  value: 2
n_sunlocked_heads:
  value: 360
num_workers:
  value: 2
prediction_window:
  value: 1
sfno_depth:
  value: 6
sfno_modes_lat:
  value: 48
sfno_modes_lon:
  value: 48
sfno_width:
  value: 96
spectral_backend:
  value: sht
weight_decay:
  value: 0
