wandb_version: 1

area_weighted_loss:
  value: false
aux_weight:
  value: 0.2
batch_size:
  value: 4
context_window:
  value: 4
date_dilation:
  value: 10
delta_minutes:
  value: 30
dropout:
  value: 0.3
epochs:
  value: 2
jpld_weight:
  value: 1
learning_rate:
  value: 0.001961480262073888
n_harmonics:
  value: 6
n_sunlocked_heads:
  value: 360
num_workers:
  value: 2
prediction_window:
  value: 4
sfno_depth:
  value: 6
sfno_modes_lat:
  value: 24
sfno_modes_lon:
  value: 64
sfno_width:
  value: 96
spectral_backend:
  value: sht
weight_decay:
  value: 1.0e-05
