wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.1
batch_size:
  value: 2
context_window:
  value: 1
date_dilation:
  value: 50
delta_minutes:
  value: 30
dropout:
  value: 0.3
epochs:
  value: 4
jpld_weight:
  value: 1
learning_rate:
  value: 0.0027415540287312684
n_harmonics:
  value: 6
n_sunlocked_heads:
  value: 360
num_workers:
  value: 2
prediction_window:
  value: 1
sfno_depth:
  value: 10
sfno_modes_lat:
  value: 48
sfno_modes_lon:
  value: 96
sfno_width:
  value: 96
spectral_backend:
  value: sht
weight_decay:
  value: 1.0e-05
