wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.1
batch_size:
  value: 4
context_window:
  value: 4
date_dilation:
  value: 5
delta_minutes:
  value: 30
dropout:
  value: 0.2
epochs:
  value: 4
jpld_weight:
  value: 2
learning_rate:
  value: 0.0012899202111210577
n_harmonics:
  value: 6
n_sunlocked_heads:
  value: 360
num_workers:
  value: 0
prediction_window:
  value: 1
sfno_depth:
  value: 6
sfno_modes_lat:
  value: 48
sfno_modes_lon:
  value: 96
sfno_width:
  value: 48
spectral_backend:
  value: sht
weight_decay:
  value: 0.0001
