wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.3
batch_size:
  value: 1
context_window:
  value: 12
date_dilation:
  value: 10
delta_minutes:
  value: 15
dropout:
  value: 0.1
epochs:
  value: 6
jpld_weight:
  value: 1
learning_rate:
  value: 0.0007961720333355816
n_harmonics:
  value: 6
n_sunlocked_heads:
  value: 180
num_workers:
  value: 0
prediction_window:
  value: 8
sfno_depth:
  value: 6
sfno_modes_lat:
  value: 32
sfno_modes_lon:
  value: 48
sfno_width:
  value: 64
spectral_backend:
  value: rfft
weight_decay:
  value: 1.0e-06
