wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.1
batch_size:
  value: 1
context_window:
  value: 8
date_dilation:
  value: 1
delta_minutes:
  value: 15
dropout:
  value: 0.2
epochs:
  value: 2
jpld_weight:
  value: 0.8
learning_rate:
  value: 0.00017310966363615526
n_harmonics:
  value: 1
n_sunlocked_heads:
  value: 360
num_workers:
  value: 2
prediction_window:
  value: 1
sfno_depth:
  value: 12
sfno_modes_lat:
  value: 24
sfno_modes_lon:
  value: 64
sfno_width:
  value: 128
spectral_backend:
  value: sht
weight_decay:
  value: 0.0001
