wandb_version: 1

area_weighted_loss:
  value: false
aux_weight:
  value: 0.3
batch_size:
  value: 2
context_window:
  value: 1
date_dilation:
  value: 50
delta_minutes:
  value: 15
dropout:
  value: 0.2
epochs:
  value: 2
jpld_weight:
  value: 1
learning_rate:
  value: 3.149891497858792e-05
n_harmonics:
  value: 6
n_sunlocked_heads:
  value: 180
num_workers:
  value: 0
prediction_window:
  value: 1
sfno_depth:
  value: 8
sfno_modes_lat:
  value: 24
sfno_modes_lon:
  value: 96
sfno_width:
  value: 64
spectral_backend:
  value: rfft
weight_decay:
  value: 0
