wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.2
batch_size:
  value: 4
context_window:
  value: 1
date_dilation:
  value: 1
delta_minutes:
  value: 30
dropout:
  value: 0.15
epochs:
  value: 4
jpld_weight:
  value: 1
learning_rate:
  value: 0.0013402804269434156
n_harmonics:
  value: 1
n_sunlocked_heads:
  value: 180
num_workers:
  value: 2
prediction_window:
  value: 1
sfno_depth:
  value: 8
sfno_modes_lat:
  value: 24
sfno_modes_lon:
  value: 64
sfno_width:
  value: 128
spectral_backend:
  value: sht
weight_decay:
  value: 0
