wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.1
batch_size:
  value: 1
context_window:
  value: 8
date_dilation:
  value: 5
delta_minutes:
  value: 15
dropout:
  value: 0.1
epochs:
  value: 2
jpld_weight:
  value: 2
learning_rate:
  value: 3.759550435553537e-05
n_harmonics:
  value: 6
n_sunlocked_heads:
  value: 180
num_workers:
  value: 1
prediction_window:
  value: 4
sfno_depth:
  value: 12
sfno_modes_lat:
  value: 48
sfno_modes_lon:
  value: 64
sfno_width:
  value: 48
spectral_backend:
  value: sht
weight_decay:
  value: 1.0e-06
