wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.2
batch_size:
  value: 1
context_window:
  value: 8
date_dilation:
  value: 20
delta_minutes:
  value: 30
dropout:
  value: 0.15
epochs:
  value: 4
jpld_weight:
  value: 1
learning_rate:
  value: 0.0006119378557055905
n_harmonics:
  value: 6
n_sunlocked_heads:
  value: 360
num_workers:
  value: 2
prediction_window:
  value: 1
sfno_depth:
  value: 8
sfno_modes_lat:
  value: 32
sfno_modes_lon:
  value: 48
sfno_width:
  value: 96
spectral_backend:
  value: sht
weight_decay:
  value: 0.0001
