wandb_version: 1

area_weighted_loss:
  value: false
aux_weight:
  value: 0.1
batch_size:
  value: 2
context_window:
  value: 1
date_dilation:
  value: 10
delta_minutes:
  value: 30
dropout:
  value: 0.3
epochs:
  value: 6
jpld_weight:
  value: 0.8
learning_rate:
  value: 0.0007208117035533623
n_harmonics:
  value: 3
n_sunlocked_heads:
  value: 180
num_workers:
  value: 2
prediction_window:
  value: 1
sfno_depth:
  value: 10
sfno_modes_lat:
  value: 32
sfno_modes_lon:
  value: 48
sfno_width:
  value: 96
spectral_backend:
  value: rfft
weight_decay:
  value: 1.0e-05
