wandb_version: 1

area_weighted_loss:
  value: false
aux_weight:
  value: 0.5
batch_size:
  value: 4
context_window:
  value: 8
date_dilation:
  value: 10
delta_minutes:
  value: 15
dropout:
  value: 0.3
epochs:
  value: 2
jpld_weight:
  value: 2
learning_rate:
  value: 0.0004295455838822372
n_harmonics:
  value: 2
n_sunlocked_heads:
  value: 360
num_workers:
  value: 1
prediction_window:
  value: 4
sfno_depth:
  value: 6
sfno_modes_lat:
  value: 24
sfno_modes_lon:
  value: 48
sfno_width:
  value: 64
spectral_backend:
  value: sht
weight_decay:
  value: 1.0e-05
