wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.1
batch_size:
  value: 1
context_window:
  value: 8
date_dilation:
  value: 10
delta_minutes:
  value: 30
dropout:
  value: 0.15
epochs:
  value: 4
jpld_weight:
  value: 2
learning_rate:
  value: 0.00056681868413683
n_harmonics:
  value: 8
n_sunlocked_heads:
  value: 360
num_workers:
  value: 2
prediction_window:
  value: 1
sfno_depth:
  value: 6
sfno_modes_lat:
  value: 32
sfno_modes_lon:
  value: 48
sfno_width:
  value: 96
spectral_backend:
  value: rfft
weight_decay:
  value: 1.0e-05
