wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.5
batch_size:
  value: 4
context_window:
  value: 8
date_dilation:
  value: 5
delta_minutes:
  value: 15
dropout:
  value: 0.2
epochs:
  value: 4
jpld_weight:
  value: 1
learning_rate:
  value: 0.00014098877098877877
n_harmonics:
  value: 6
n_sunlocked_heads:
  value: 180
num_workers:
  value: 1
prediction_window:
  value: 4
sfno_depth:
  value: 8
sfno_modes_lat:
  value: 48
sfno_modes_lon:
  value: 64
sfno_width:
  value: 128
spectral_backend:
  value: rfft
weight_decay:
  value: 0.0001
