wandb_version: 1

area_weighted_loss:
  value: false
aux_weight:
  value: 0.1
batch_size:
  value: 1
context_window:
  value: 12
date_dilation:
  value: 1
delta_minutes:
  value: 30
dropout:
  value: 0.1
epochs:
  value: 4
jpld_weight:
  value: 1
learning_rate:
  value: 0.001031442462977908
n_harmonics:
  value: 2
n_sunlocked_heads:
  value: 360
num_workers:
  value: 1
prediction_window:
  value: 1
sfno_depth:
  value: 12
sfno_modes_lat:
  value: 32
sfno_modes_lon:
  value: 48
sfno_width:
  value: 128
spectral_backend:
  value: sht
weight_decay:
  value: 0
