wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.3
batch_size:
  value: 1
context_window:
  value: 8
date_dilation:
  value: 50
delta_minutes:
  value: 30
dropout:
  value: 0.1
epochs:
  value: 4
jpld_weight:
  value: 2
learning_rate:
  value: 5.1295190529104784e-05
n_harmonics:
  value: 2
n_sunlocked_heads:
  value: 360
num_workers:
  value: 2
prediction_window:
  value: 1
sfno_depth:
  value: 6
sfno_modes_lat:
  value: 24
sfno_modes_lon:
  value: 48
sfno_width:
  value: 128
spectral_backend:
  value: sht
weight_decay:
  value: 1.0e-05
