wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.3
batch_size:
  value: 1
context_window:
  value: 12
date_dilation:
  value: 1
delta_minutes:
  value: 30
dropout:
  value: 0.2
epochs:
  value: 4
jpld_weight:
  value: 2
learning_rate:
  value: 9.077484308771704e-05
n_harmonics:
  value: 3
n_sunlocked_heads:
  value: 360
num_workers:
  value: 2
prediction_window:
  value: 1
sfno_depth:
  value: 10
sfno_modes_lat:
  value: 32
sfno_modes_lon:
  value: 48
sfno_width:
  value: 64
spectral_backend:
  value: sht
weight_decay:
  value: 1.0e-05
