wandb_version: 1

area_weighted_loss:
  value: false
aux_weight:
  value: 0.3
batch_size:
  value: 1
context_window:
  value: 8
date_dilation:
  value: 1
delta_minutes:
  value: 30
dropout:
  value: 0.3
epochs:
  value: 4
jpld_weight:
  value: 0.8
learning_rate:
  value: 0.00030788788508395937
n_harmonics:
  value: 6
n_sunlocked_heads:
  value: 360
num_workers:
  value: 1
prediction_window:
  value: 8
sfno_depth:
  value: 12
sfno_modes_lat:
  value: 24
sfno_modes_lon:
  value: 64
sfno_width:
  value: 48
spectral_backend:
  value: sht
weight_decay:
  value: 0.0001
