wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.1
batch_size:
  value: 1
context_window:
  value: 1
date_dilation:
  value: 20
delta_minutes:
  value: 30
dropout:
  value: 0.2
epochs:
  value: 4
jpld_weight:
  value: 2
learning_rate:
  value: 2.3631509870698797e-05
n_harmonics:
  value: 2
n_sunlocked_heads:
  value: 180
num_workers:
  value: 2
prediction_window:
  value: 1
sfno_depth:
  value: 8
sfno_modes_lat:
  value: 48
sfno_modes_lon:
  value: 64
sfno_width:
  value: 96
spectral_backend:
  value: sht
weight_decay:
  value: 1.0e-05
