wandb_version: 1

area_weighted_loss:
  value: false
aux_weight:
  value: 0.2
batch_size:
  value: 1
context_window:
  value: 4
date_dilation:
  value: 20
delta_minutes:
  value: 30
dropout:
  value: 0.2
epochs:
  value: 2
jpld_weight:
  value: 2
learning_rate:
  value: 0.0006120762521087429
n_harmonics:
  value: 1
n_sunlocked_heads:
  value: 180
num_workers:
  value: 1
prediction_window:
  value: 1
sfno_depth:
  value: 8
sfno_modes_lat:
  value: 32
sfno_modes_lon:
  value: 64
sfno_width:
  value: 128
spectral_backend:
  value: sht
weight_decay:
  value: 0.0001
