wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.2
batch_size:
  value: 1
context_window:
  value: 4
date_dilation:
  value: 10
delta_minutes:
  value: 30
dropout:
  value: 0.2
epochs:
  value: 4
jpld_weight:
  value: 2
learning_rate:
  value: 0.001521474488978593
n_harmonics:
  value: 1
n_sunlocked_heads:
  value: 180
num_workers:
  value: 2
prediction_window:
  value: 1
sfno_depth:
  value: 12
sfno_modes_lat:
  value: 24
sfno_modes_lon:
  value: 48
sfno_width:
  value: 48
spectral_backend:
  value: sht
weight_decay:
  value: 1.0e-05
