wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.1
batch_size:
  value: 4
context_window:
  value: 8
date_dilation:
  value: 20
delta_minutes:
  value: 60
dropout:
  value: 0.15
epochs:
  value: 20
jpld_weight:
  value: 2
learning_rate:
  value: 0.0007479726110007876
n_harmonics:
  value: 1
n_sunlocked_heads:
  value: 360
num_workers:
  value: 0
prediction_window:
  value: 4
sfno_depth:
  value: 10
sfno_modes_lat:
  value: 32
sfno_modes_lon:
  value: 96
sfno_width:
  value: 64
spectral_backend:
  value: sht
weight_decay:
  value: 1.0e-05
