wandb_version: 1

area_weighted_loss:
  value: true
aux_weight:
  value: 0.3
batch_size:
  value: 8
context_window:
  value: 12
date_dilation:
  value: 5
delta_minutes:
  value: 60
dropout:
  value: 0.2
epochs:
  value: 2
jpld_weight:
  value: 1
learning_rate:
  value: 0.0010643140745500604
n_harmonics:
  value: 10
n_sunlocked_heads:
  value: 360
num_workers:
  value: 1
prediction_window:
  value: 8
sfno_depth:
  value: 8
sfno_modes_lat:
  value: 48
sfno_modes_lon:
  value: 64
sfno_width:
  value: 96
spectral_backend:
  value: rfft
weight_decay:
  value: 0
